name: Build and deploy Python app to Azure Web App - testazureflask

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # ✅ Required for Azure login
      contents: read   # ✅ Required for checkout

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1C956964D3944D24BF13DFE9FB769629 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0C3A025C3544F429A2D8ADA56F969DB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3736DBF254EE4DBC9D290FA1ED24C3AD }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'testazureflask'
          slot-name: 'Production'
          package: .  # 👈 Deploys everything in repo
